### PR TITLE
revert windowText so appName appears first + increased resolution of font scaling

### PR DESCRIPTION
**Pull request by kupiqu**
This pull request is associated with issue #37

### CODE REVIEW

**Comment by kupiqu** [comment]
The second commit is associated with issue #38

**Comment by kupiqu** [comment]
Sorry, I didn't find a way to separate the pull request into two

**Comment by kotelnik** [comment]
Thanks for these suggestions! Sorry I didn't merge them. It looked like too big customization code enabled by default. But it was basically a good idea - so I added a support for custom title replacing with regex and included one regex doing what you've proposed. You just need to check replacing checkbox in the settings to enable it.

As for the font scaling. That I included exactly like you proposed. Thanks a lot for your code!

**Comment by kupiqu** [comment]
Great!

**Pull request closed without merging**
