### PR TITLE
Add After Text AppMenu Option

### PR DESCRIPTION
**Pull request by bkrith**
I add new option.. appmenu after text. See my screenshot below. Sorry for bad coding i'm just learning qml. I believe that is easier way for my dummy text component! :D 
Also I dont understand why github create for me a full fork of yours project!?!?

newmenuoption

### CODE REVIEW

**Comment by MattMcHackit** [comment]
With this option active, text appears to overrun into the appmenu. Is there a way of setting the spacing?

**Comment by bkrith** [comment]
Sorry mate... I apologize.. I found a solution.. I didnt set font attributes to Item testText (dummy Text). I fix it now but... best is to wait approve from kotelnik, because maybe is there easier way to do all that!

**Comment by bkrith** [comment]
@MattMcHackit  Added also option to set the spacing and the limitation of title width from plasmoid settings

**Comment by MattMcHackit** [comment]
@bkrith That's perfect!! Thank you so much! Widget's pretty much perfect now!

**Comment by MattMcHackit** [comment]
Suggest this code is integrated, asap, @kotelnik

**Comment by bkrith** [comment]
Thank you so much! @kotelnik has did amazing work! I just tweak the already maded code!

**Comment by kotelnik** [comment]
Hi! Sorry it took me so long. I finally had time to look on the changes. First I wanted to integrate your pull request but I in the end I wanted to do the changes a bit differently. I think I've done all, You wanted to achieve with this pull. Please let me know if something is missing.

What I've done:
- settable 'Plasma Desktop' text (+ icon as a bonus)
- settable title width limit (in Appearance settings)
- option for AppMenu switching sides with icon and text and proper text width checking without fake-text
- settable AppMenu side margin

Anyway, thanks VERY much for Your code and suggestions.

**Comment by bkrith** [comment]
Yeap... that's it!! There was easier and more elegant way for do those things!(wtf?!?!... implicitWidth?!?! :D) 
I will try to learn QML... I must dig...
Thank you so much!

**Pull request closed without merging**
